<?php

/**
 * Please, do not edit this file. The configuration file for Debian
 * is located in the /etc/postfixadmin/config.inc.php file.
 */

$CONF['database_type'] = '_DBC_DBTYPE_';
$CONF['database_host'] = '_DBC_DBSERVER_';
$CONF['database_user'] = '_DBC_DBUSER_';
$CONF['database_password'] = '_DBC_DBPASS_';
$CONF['database_name'] = '_DBC_DBNAME_';

?>
